// Phase data keyed by domain slug
const phaseData = {
  'web-development': [
    { phaseNumber: 1, name: 'Internet & Web Basics', description: 'How the internet works, HTTP, browsers, DNS', estimatedDuration: '3 days' },
    { phaseNumber: 2, name: 'HTML', description: 'HTML5 structure, semantic tags, forms', estimatedDuration: '1 week' },
    { phaseNumber: 3, name: 'CSS', description: 'Styling, Flexbox, Grid, responsive design', estimatedDuration: '2 weeks' },
    { phaseNumber: 4, name: 'JavaScript', description: 'ES6+, DOM, async/await, fetch API', estimatedDuration: '3 weeks' },
    { phaseNumber: 5, name: 'Git & GitHub', description: 'Version control, branches, PRs', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'React.js', description: 'Components, hooks, state management', estimatedDuration: '3 weeks' },
    { phaseNumber: 7, name: 'Backend with Node.js & Express', description: 'REST APIs, routing, middleware', estimatedDuration: '2 weeks' },
    { phaseNumber: 8, name: 'Database with MongoDB/SQL', description: 'CRUD, schemas, queries', estimatedDuration: '2 weeks' },
    { phaseNumber: 9, name: 'Authentication & Authorization', description: 'JWT, OAuth, sessions', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'API Integration', description: 'Third-party APIs, webhooks', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Deployment', description: 'Vercel, Render, CI/CD basics', estimatedDuration: '1 week' },
    { phaseNumber: 12, name: 'Final Full-Stack Project', description: 'Build a complete MERN application', estimatedDuration: '2 weeks' }
  ],
  'data-science': [
    { phaseNumber: 1, name: 'Python Basics', description: 'Syntax, data types, control flow, functions', estimatedDuration: '2 weeks' },
    { phaseNumber: 2, name: 'Math for Data Science', description: 'Linear algebra, calculus basics', estimatedDuration: '2 weeks' },
    { phaseNumber: 3, name: 'Statistics', description: 'Descriptive stats, probability, distributions', estimatedDuration: '2 weeks' },
    { phaseNumber: 4, name: 'NumPy', description: 'Arrays, matrix operations, broadcasting', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'Pandas', description: 'DataFrames, data manipulation, cleaning', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'Data Visualization', description: 'Matplotlib, Seaborn, Plotly', estimatedDuration: '1 week' },
    { phaseNumber: 7, name: 'Machine Learning Basics', description: 'Supervised/unsupervised, scikit-learn', estimatedDuration: '3 weeks' },
    { phaseNumber: 8, name: 'Model Evaluation', description: 'Metrics, cross-validation, hyperparameter tuning', estimatedDuration: '1 week' },
    { phaseNumber: 9, name: 'Projects', description: 'Mini projects for each ML concept', estimatedDuration: '2 weeks' },
    { phaseNumber: 10, name: 'Final Data Science Project', description: 'End-to-end ML pipeline', estimatedDuration: '2 weeks' }
  ],
  'data-analytics': [
    { phaseNumber: 1, name: 'Excel Basics', description: 'Formulas, pivot tables, charts', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'SQL', description: 'Queries, joins, aggregations', estimatedDuration: '2 weeks' },
    { phaseNumber: 3, name: 'Python Basics', description: 'Core Python for analytics', estimatedDuration: '2 weeks' },
    { phaseNumber: 4, name: 'Pandas', description: 'Data manipulation and analysis', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'Data Cleaning', description: 'Handling missing data, outliers', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'Data Visualization', description: 'Charts, graphs, storytelling with data', estimatedDuration: '1 week' },
    { phaseNumber: 7, name: 'Power BI / Tableau', description: 'BI tools and dashboards', estimatedDuration: '2 weeks' },
    { phaseNumber: 8, name: 'Business Metrics', description: 'KPIs, funnels, cohort analysis', estimatedDuration: '1 week' },
    { phaseNumber: 9, name: 'Dashboard Project', description: 'Build interactive dashboards', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'Final Analytics Case Study', description: 'Real-world business analytics project', estimatedDuration: '2 weeks' }
  ],
  'devops-engineering': [
    { phaseNumber: 1, name: 'Linux Basics', description: 'Commands, file system, permissions', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'Networking Basics', description: 'TCP/IP, DNS, HTTP, firewalls', estimatedDuration: '1 week' },
    { phaseNumber: 3, name: 'Git & GitHub', description: 'Version control for DevOps', estimatedDuration: '3 days' },
    { phaseNumber: 4, name: 'Shell Scripting', description: 'Bash scripting and automation', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'Docker', description: 'Containers, images, Docker Compose', estimatedDuration: '2 weeks' },
    { phaseNumber: 6, name: 'Kubernetes', description: 'Pods, services, deployments, scaling', estimatedDuration: '2 weeks' },
    { phaseNumber: 7, name: 'CI/CD', description: 'GitHub Actions, Jenkins, pipelines', estimatedDuration: '2 weeks' },
    { phaseNumber: 8, name: 'Terraform', description: 'Infrastructure as code', estimatedDuration: '1 week' },
    { phaseNumber: 9, name: 'Ansible', description: 'Configuration management', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'Monitoring & Logging', description: 'Prometheus, Grafana, ELK stack', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Cloud Basics', description: 'AWS/GCP/Azure fundamentals', estimatedDuration: '1 week' },
    { phaseNumber: 12, name: 'Final DevOps Pipeline Project', description: 'Full CI/CD pipeline with Docker & K8s', estimatedDuration: '2 weeks' }
  ],
  'cloud-computing': [
    { phaseNumber: 1, name: 'Cloud Fundamentals', description: 'IaaS, PaaS, SaaS, cloud models', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'Networking Basics', description: 'VPC, subnets, routing, security groups', estimatedDuration: '1 week' },
    { phaseNumber: 3, name: 'Linux Basics', description: 'Linux for cloud administration', estimatedDuration: '1 week' },
    { phaseNumber: 4, name: 'AWS Basics', description: 'EC2, S3, IAM, Lambda', estimatedDuration: '2 weeks' },
    { phaseNumber: 5, name: 'Azure Basics', description: 'Azure VM, Blob Storage, AAD', estimatedDuration: '2 weeks' },
    { phaseNumber: 6, name: 'Google Cloud Basics', description: 'GCE, GCS, Cloud Run', estimatedDuration: '2 weeks' },
    { phaseNumber: 7, name: 'IAM & Security', description: 'Identity, roles, policies', estimatedDuration: '1 week' },
    { phaseNumber: 8, name: 'Compute Services', description: 'VMs, containers, serverless compute', estimatedDuration: '1 week' },
    { phaseNumber: 9, name: 'Storage Services', description: 'Object, block, file storage', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'Databases in Cloud', description: 'RDS, DynamoDB, Firestore', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Serverless', description: 'AWS Lambda, Cloud Functions', estimatedDuration: '1 week' },
    { phaseNumber: 12, name: 'Monitoring & Cost Optimization', description: 'CloudWatch, cost controls', estimatedDuration: '1 week' },
    { phaseNumber: 13, name: 'Final Cloud Deployment Project', description: 'Deploy scalable app on cloud', estimatedDuration: '2 weeks' }
  ],
  'cybersecurity': [
    { phaseNumber: 1, name: 'Networking Basics', description: 'OSI model, TCP/IP, protocols', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'Linux Basics', description: 'Linux for security', estimatedDuration: '1 week' },
    { phaseNumber: 3, name: 'Web Basics', description: 'HTTP, cookies, sessions, web security', estimatedDuration: '1 week' },
    { phaseNumber: 4, name: 'Security Fundamentals', description: 'CIA triad, threats, vulnerabilities', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'Cryptography Basics', description: 'Encryption, hashing, PKI', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'OWASP Top 10', description: 'Top web vulnerabilities', estimatedDuration: '2 weeks' },
    { phaseNumber: 7, name: 'Vulnerability Assessment', description: 'Scanning, enumeration, reporting', estimatedDuration: '1 week' },
    { phaseNumber: 8, name: 'Ethical Hacking Labs', description: 'Metasploit, Burp Suite, Kali Linux', estimatedDuration: '2 weeks' },
    { phaseNumber: 9, name: 'CTF Practice', description: 'Capture the Flag challenges', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'Security Tools', description: 'Wireshark, Nmap, SIEM tools', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Final Security Audit Project', description: 'Full penetration test report', estimatedDuration: '2 weeks' }
  ],
  'app-development': [
    { phaseNumber: 1, name: 'Programming Basics', description: 'Java/Kotlin/Dart fundamentals', estimatedDuration: '2 weeks' },
    { phaseNumber: 2, name: 'UI Basics', description: 'Mobile UI principles, layouts', estimatedDuration: '1 week' },
    { phaseNumber: 3, name: 'Android Basics', description: 'Activities, intents, lifecycle', estimatedDuration: '2 weeks' },
    { phaseNumber: 4, name: 'Kotlin/Java Basics', description: 'OOP, collections, coroutines', estimatedDuration: '2 weeks' },
    { phaseNumber: 5, name: 'Flutter Basics', description: 'Widgets, layouts, navigation', estimatedDuration: '2 weeks' },
    { phaseNumber: 6, name: 'State Management', description: 'Provider, Riverpod, BLoC', estimatedDuration: '1 week' },
    { phaseNumber: 7, name: 'APIs Integration', description: 'REST APIs, HTTP, JSON', estimatedDuration: '1 week' },
    { phaseNumber: 8, name: 'Local Storage', description: 'SQLite, SharedPreferences, Hive', estimatedDuration: '1 week' },
    { phaseNumber: 9, name: 'Authentication', description: 'Firebase Auth, Google Sign-In', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'App Deployment', description: 'Play Store, App Store publishing', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Final Mobile App Project', description: 'Full-featured cross-platform app', estimatedDuration: '2 weeks' }
  ],
  'ai-ml-engineering': [
    { phaseNumber: 1, name: 'Python Basics', description: 'Python for ML', estimatedDuration: '2 weeks' },
    { phaseNumber: 2, name: 'Math for ML', description: 'Linear algebra, calculus, optimization', estimatedDuration: '2 weeks' },
    { phaseNumber: 3, name: 'Statistics', description: 'Probability, distributions, Bayes', estimatedDuration: '1 week' },
    { phaseNumber: 4, name: 'NumPy', description: 'Array operations for ML', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'Pandas', description: 'Data wrangling for ML', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'Machine Learning', description: 'Supervised, unsupervised, scikit-learn', estimatedDuration: '3 weeks' },
    { phaseNumber: 7, name: 'Deep Learning Basics', description: 'Neural networks, TensorFlow, PyTorch', estimatedDuration: '3 weeks' },
    { phaseNumber: 8, name: 'NLP Basics', description: 'Text processing, transformers', estimatedDuration: '2 weeks' },
    { phaseNumber: 9, name: 'Computer Vision Basics', description: 'Image classification, CNNs, OpenCV', estimatedDuration: '2 weeks' },
    { phaseNumber: 10, name: 'Model Deployment', description: 'FastAPI, Flask, Docker for ML', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Final AI/ML Project', description: 'Build and deploy a production ML model', estimatedDuration: '2 weeks' }
  ],
  'blockchain-development': [
    { phaseNumber: 1, name: 'Blockchain Fundamentals', description: 'Blocks, chains, consensus, wallets', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'Cryptography Basics', description: 'Hashing, digital signatures, keys', estimatedDuration: '1 week' },
    { phaseNumber: 3, name: 'Ethereum Basics', description: 'EVM, accounts, gas, transactions', estimatedDuration: '1 week' },
    { phaseNumber: 4, name: 'Solidity', description: 'Smart contract language', estimatedDuration: '3 weeks' },
    { phaseNumber: 5, name: 'Smart Contracts', description: 'ERC-20, ERC-721, security patterns', estimatedDuration: '2 weeks' },
    { phaseNumber: 6, name: 'Web3.js / Ethers.js', description: 'Interacting with blockchain from JS', estimatedDuration: '2 weeks' },
    { phaseNumber: 7, name: 'DApp Frontend', description: 'React + Web3 integration', estimatedDuration: '2 weeks' },
    { phaseNumber: 8, name: 'Wallet Integration', description: 'MetaMask, WalletConnect', estimatedDuration: '1 week' },
    { phaseNumber: 9, name: 'Smart Contract Testing', description: 'Hardhat, Foundry, test suites', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'Deployment', description: 'Testnet and mainnet deployment', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Final DApp Project', description: 'Full decentralized application', estimatedDuration: '2 weeks' }
  ],
  'ui-ux-design': [
    { phaseNumber: 1, name: 'Design Fundamentals', description: 'Principles of visual design', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'Color Theory', description: 'Color palettes, psychology, accessibility', estimatedDuration: '3 days' },
    { phaseNumber: 3, name: 'Typography', description: 'Font selection, hierarchy, spacing', estimatedDuration: '3 days' },
    { phaseNumber: 4, name: 'Layout & Spacing', description: 'Grid systems, whitespace, alignment', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'User Research', description: 'User interviews, surveys, personas', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'Wireframing', description: 'Low-fi wireframes, user flows', estimatedDuration: '1 week' },
    { phaseNumber: 7, name: 'Prototyping', description: 'Clickable prototypes, animations', estimatedDuration: '1 week' },
    { phaseNumber: 8, name: 'Figma', description: 'Components, auto-layout, design systems', estimatedDuration: '2 weeks' },
    { phaseNumber: 9, name: 'Design Systems', description: 'Style guides, component libraries', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'Usability Testing', description: 'A/B testing, user feedback', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Portfolio Project', description: 'Complete UI/UX case study', estimatedDuration: '2 weeks' }
  ],
  'database-administration': [
    { phaseNumber: 1, name: 'DBMS Basics', description: 'Relational model, ER diagrams', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'SQL Basics', description: 'DDL, DML, queries', estimatedDuration: '2 weeks' },
    { phaseNumber: 3, name: 'SQL Joins', description: 'Inner, outer, cross joins', estimatedDuration: '1 week' },
    { phaseNumber: 4, name: 'Indexing', description: 'B-tree, hash indexes, query optimization', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'Normalization', description: '1NF, 2NF, 3NF, BCNF', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'Transactions', description: 'ACID, concurrency, deadlocks', estimatedDuration: '1 week' },
    { phaseNumber: 7, name: 'Backup & Recovery', description: 'Backup strategies, point-in-time recovery', estimatedDuration: '1 week' },
    { phaseNumber: 8, name: 'User Management', description: 'Roles, privileges, security', estimatedDuration: '3 days' },
    { phaseNumber: 9, name: 'Performance Tuning', description: 'Query plans, caching, partitioning', estimatedDuration: '2 weeks' },
    { phaseNumber: 10, name: 'Security', description: 'Encryption, auditing, compliance', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Final Database Project', description: 'Design and optimize production DB', estimatedDuration: '2 weeks' }
  ],
  'software-testing-qa': [
    { phaseNumber: 1, name: 'Testing Fundamentals', description: 'Types of testing, QA lifecycle', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'Manual Testing', description: 'Test planning, execution', estimatedDuration: '1 week' },
    { phaseNumber: 3, name: 'Test Cases', description: 'Writing effective test cases', estimatedDuration: '1 week' },
    { phaseNumber: 4, name: 'Bug Reports', description: 'Defect lifecycle, reporting tools', estimatedDuration: '3 days' },
    { phaseNumber: 5, name: 'SDLC / STLC', description: 'Development and testing lifecycle', estimatedDuration: '3 days' },
    { phaseNumber: 6, name: 'API Testing', description: 'REST API testing concepts', estimatedDuration: '1 week' },
    { phaseNumber: 7, name: 'Postman', description: 'API testing with Postman', estimatedDuration: '1 week' },
    { phaseNumber: 8, name: 'Automation Basics', description: 'Test automation principles', estimatedDuration: '1 week' },
    { phaseNumber: 9, name: 'Selenium / Cypress', description: 'Browser automation frameworks', estimatedDuration: '2 weeks' },
    { phaseNumber: 10, name: 'Performance Testing Basics', description: 'JMeter, load testing', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Final QA Project', description: 'Complete test suite for a web app', estimatedDuration: '2 weeks' }
  ],
  'competitive-programming-dsa': [
    { phaseNumber: 1, name: 'Programming Basics', description: 'Language syntax, I/O, basics', estimatedDuration: '1 week' },
    { phaseNumber: 2, name: 'Time & Space Complexity', description: 'Big O, analysis', estimatedDuration: '3 days' },
    { phaseNumber: 3, name: 'Arrays', description: 'Array operations, two pointers, sliding window', estimatedDuration: '1 week' },
    { phaseNumber: 4, name: 'Strings', description: 'String manipulation, pattern matching', estimatedDuration: '1 week' },
    { phaseNumber: 5, name: 'Recursion', description: 'Recursion, backtracking', estimatedDuration: '1 week' },
    { phaseNumber: 6, name: 'Sorting', description: 'Merge sort, quick sort, heap sort', estimatedDuration: '1 week' },
    { phaseNumber: 7, name: 'Searching', description: 'Binary search, variations', estimatedDuration: '3 days' },
    { phaseNumber: 8, name: 'Hashing', description: 'Hash maps, sets, frequency counting', estimatedDuration: '3 days' },
    { phaseNumber: 9, name: 'Stack & Queue', description: 'Stack, queue, deque applications', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'Linked List', description: 'Singly, doubly, circular lists', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Trees', description: 'BST, AVL, heaps, traversals', estimatedDuration: '2 weeks' },
    { phaseNumber: 12, name: 'Graphs', description: 'BFS, DFS, shortest paths', estimatedDuration: '2 weeks' },
    { phaseNumber: 13, name: 'Dynamic Programming', description: 'Memoization, tabulation, classic DP', estimatedDuration: '2 weeks' },
    { phaseNumber: 14, name: 'Greedy & Final Challenge', description: 'Greedy algorithms and contest', estimatedDuration: '1 week' }
  ],
  'open-source-contribution': [
    { phaseNumber: 1, name: 'Git Basics', description: 'Init, commit, push, pull', estimatedDuration: '3 days' },
    { phaseNumber: 2, name: 'GitHub Basics', description: 'Repos, forks, stars, issues', estimatedDuration: '3 days' },
    { phaseNumber: 3, name: 'Markdown', description: 'README, docs, formatting', estimatedDuration: '2 days' },
    { phaseNumber: 4, name: 'Issues', description: 'Reading issues, good-first-issues', estimatedDuration: '3 days' },
    { phaseNumber: 5, name: 'Pull Requests', description: 'Creating, reviewing PRs', estimatedDuration: '3 days' },
    { phaseNumber: 6, name: 'Branching', description: 'Branch strategies, merge conflicts', estimatedDuration: '3 days' },
    { phaseNumber: 7, name: 'Code Review', description: 'Reviewing others code, feedback', estimatedDuration: '3 days' },
    { phaseNumber: 8, name: 'Documentation Contribution', description: 'Improving docs, wikis', estimatedDuration: '3 days' },
    { phaseNumber: 9, name: 'Beginner-Friendly Repositories', description: 'First contributions to real projects', estimatedDuration: '1 week' },
    { phaseNumber: 10, name: 'First Contribution', description: 'Merged PR in a popular repo', estimatedDuration: '1 week' },
    { phaseNumber: 11, name: 'Open Source Portfolio', description: 'Build your contribution record', estimatedDuration: '2 weeks' }
  ]
};

module.exports = phaseData;
